[build]  
  functions = "netlify/functions"  
  publish = "public"  

[dev]  
  framework = "#static"  
  publish = "public"  
  port = 8888  
  autoLaunch = true  

[[redirects]]  
  from = "/api/*"  
  to = "/.netlify/functions/:splat"  
  status = 200  
  
[[redirects]]  
  from = "/course/*"  
  to = "/course.html"  
  status = 200  

[[redirects]]  
  from = "/course/*/lesson/*"  
  to = "/lesson.html"  
  status = 200  

